trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildViewer
        displayName: Build viewer
        steps:
          - script: dotnet tool restore
            displayName: restore nuke tool
          - script: dotnet nuke Publish -Runtime win-x86
            displayName: publish application win-x64
          - publish: output
            artifact: excursion360-desktop-win-x64
            displayName: publish executable artifact