trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include:
    - v*

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: BuildViewer
      displayName: Build viewer
      strategy:
        matrix:
          win-x64:
            imageName: windows-latest
            runtime: win-x64
          win-x86:
            imageName: windows-latest
            runtime: win-x86
      pool:
        vmImage: $(imageName)
      steps:
        - script: dotnet tool restore
          displayName: restore nuke tool
        - script: dotnet nuke Publish -Runtime $(runtime)
          displayName: publish application $(runtime)
        - publish: output
          artifact: excursion360-desktop-build-$(runtime)
          displayName: publish executable artifact
    - job: PublishReleaseNotes
      displayName: Publish release notes
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - publish: ReleaseNotes.md
        artifact: excursion360-desktop-release-notes
        displayName: publish release notes

- stage: Deploy
  displayName: Deploy
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: DeployViewer
      displayName: Deploy viewer
      steps:
        - checkout: none
        - download: current
        - task: GitHubRelease@1
          inputs:
            gitHubConnection: 'CAPCHIK'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'gitTag'
            releaseNotesFilePath: '$(Pipeline.Workspace)/excursion360-desktop-release-notes/ReleaseNotes.md'
            assets: '$(Pipeline.Workspace)/excursion360-desktop-build*/*'
            isDraft: true
            changeLogCompareToRelease: 'lastFullRelease'
            changeLogType: 'commitBased'
