trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

stages:
- stage: Build
  displayName: Build
  pool:
    vmImage: 'windows-latest'
  jobs:
    - job: BuildViewer
      displayName: Build viewer
      steps:
        - script: dotnet tool restore
          displayName: restore nuke tool
        - script: dotnet nuke Publish -Runtime win-x86
          displayName: publish application win-x64
        - publish: output
          artifact: excursion360-desktop-win-x64
          displayName: publish executable artifact

- stage: Deploy
  displayName: Deploy
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: DeployViewer
      displayName: Deploy viewer
      steps:
        - checkout: none
        - download: current
        - task: GitHubRelease@1
          inputs:
            gitHubConnection: 'CAPCHIK'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'gitTag'
            releaseNotesFilePath: 'ReleaseNotes.md'
            assets: '$(Pipeline.Workspace)/excursion360-desktop-win-x64/*'
            isDraft: true
            changeLogCompareToRelease: 'lastFullRelease'
            changeLogType: 'commitBased'
